// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Usuarios.API.Infrastructure.Data;

#nullable disable

namespace Usuarios.API.Infra.Migrations
{
    [DbContext(typeof(UsuarioContext))]
    [Migration("20260217170028_newCreate")]
    partial class newCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Usuarios.API.Domain.Entities.CategoriaFinanceira", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("categoria_financeira", (string)null);
                });

            modelBuilder.Entity("Usuarios.API.Domain.Entities.ComprovacaoTarefa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataEnvio")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataValidacao")
                        .HasColumnType("datetime2");

                    b.Property<int>("TarefaId")
                        .HasColumnType("int");

                    b.Property<string>("UrlFoto")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("Validada")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("TarefaId");

                    b.ToTable("comprovacao_tarefa", (string)null);
                });

            modelBuilder.Entity("Usuarios.API.Domain.Entities.Mesada", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Ano")
                        .HasColumnType("int");

                    b.Property<int>("FilhoId")
                        .HasColumnType("int");

                    b.Property<int>("Mes")
                        .HasColumnType("int");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("FilhoId");

                    b.ToTable("mesada", (string)null);
                });

            modelBuilder.Entity("Usuarios.API.Domain.Entities.PaisFilhos", b =>
                {
                    b.Property<int>("PaiId")
                        .HasColumnType("int");

                    b.Property<int>("FilhoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataVinculo")
                        .HasColumnType("datetime2");

                    b.HasKey("PaiId", "FilhoId");

                    b.HasIndex("FilhoId");

                    b.ToTable("pais_filhos", (string)null);
                });

            modelBuilder.Entity("Usuarios.API.Domain.Entities.Pontuacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataRegistro")
                        .HasColumnType("datetime2");

                    b.Property<int>("FilhoId")
                        .HasColumnType("int");

                    b.Property<int>("Pontos")
                        .HasColumnType("int");

                    b.Property<int>("TarefaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FilhoId");

                    b.HasIndex("TarefaId")
                        .IsUnique();

                    b.ToTable("pontuacao", (string)null);
                });

            modelBuilder.Entity("Usuarios.API.Domain.Entities.Recompensa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativa")
                        .HasColumnType("bit");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("FilhoId")
                        .HasColumnType("int");

                    b.Property<int>("PontosNecessarios")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FilhoId");

                    b.ToTable("recompensa", (string)null);
                });

            modelBuilder.Entity("Usuarios.API.Domain.Entities.RecompensaResgatada", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataResgate")
                        .HasColumnType("datetime2");

                    b.Property<int>("FilhoId")
                        .HasColumnType("int");

                    b.Property<int>("RecompensaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FilhoId");

                    b.HasIndex("RecompensaId");

                    b.ToTable("recompensa_resgatada", (string)null);
                });

            modelBuilder.Entity("Usuarios.API.Domain.Entities.RegistroFinanceiro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("FilhoId")
                        .HasColumnType("int");

                    b.Property<int>("MesadaId")
                        .HasColumnType("int");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("FilhoId");

                    b.HasIndex("MesadaId");

                    b.ToTable("registro_financeiro", (string)null);
                });

            modelBuilder.Entity("Usuarios.API.Domain.Entities.Tarefa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("FilhoId")
                        .HasColumnType("int");

                    b.Property<int>("Pontos")
                        .HasColumnType("int");

                    b.Property<DateTime>("Prazo")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("FilhoId");

                    b.ToTable("tarefa", (string)null);
                });

            modelBuilder.Entity("Usuarios.API.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("usuario", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Usuarios.API.Domain.Entities.Filho", b =>
                {
                    b.HasBaseType("Usuarios.API.Domain.Entities.Usuario");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("datetime2");

                    b.ToTable("filho", (string)null);
                });

            modelBuilder.Entity("Usuarios.API.Domain.Entities.Pai", b =>
                {
                    b.HasBaseType("Usuarios.API.Domain.Entities.Usuario");

                    b.ToTable("pai", (string)null);
                });

            modelBuilder.Entity("Usuarios.API.Domain.Entities.ComprovacaoTarefa", b =>
                {
                    b.HasOne("Usuarios.API.Domain.Entities.Tarefa", "Tarefa")
                        .WithMany()
                        .HasForeignKey("TarefaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tarefa");
                });

            modelBuilder.Entity("Usuarios.API.Domain.Entities.Mesada", b =>
                {
                    b.HasOne("Usuarios.API.Domain.Entities.Filho", "Filho")
                        .WithMany()
                        .HasForeignKey("FilhoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Filho");
                });

            modelBuilder.Entity("Usuarios.API.Domain.Entities.PaisFilhos", b =>
                {
                    b.HasOne("Usuarios.API.Domain.Entities.Filho", "Filho")
                        .WithMany()
                        .HasForeignKey("FilhoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Usuarios.API.Domain.Entities.Pai", "Pai")
                        .WithMany("PaisFilhos")
                        .HasForeignKey("PaiId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Filho");

                    b.Navigation("Pai");
                });

            modelBuilder.Entity("Usuarios.API.Domain.Entities.Pontuacao", b =>
                {
                    b.HasOne("Usuarios.API.Domain.Entities.Filho", "Filho")
                        .WithMany()
                        .HasForeignKey("FilhoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Usuarios.API.Domain.Entities.Tarefa", "Tarefa")
                        .WithOne()
                        .HasForeignKey("Usuarios.API.Domain.Entities.Pontuacao", "TarefaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Filho");

                    b.Navigation("Tarefa");
                });

            modelBuilder.Entity("Usuarios.API.Domain.Entities.Recompensa", b =>
                {
                    b.HasOne("Usuarios.API.Domain.Entities.Filho", "Filho")
                        .WithMany()
                        .HasForeignKey("FilhoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Filho");
                });

            modelBuilder.Entity("Usuarios.API.Domain.Entities.RecompensaResgatada", b =>
                {
                    b.HasOne("Usuarios.API.Domain.Entities.Filho", "Filho")
                        .WithMany()
                        .HasForeignKey("FilhoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Usuarios.API.Domain.Entities.Recompensa", "Recompensa")
                        .WithMany()
                        .HasForeignKey("RecompensaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Filho");

                    b.Navigation("Recompensa");
                });

            modelBuilder.Entity("Usuarios.API.Domain.Entities.RegistroFinanceiro", b =>
                {
                    b.HasOne("Usuarios.API.Domain.Entities.CategoriaFinanceira", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Usuarios.API.Domain.Entities.Filho", "Filho")
                        .WithMany()
                        .HasForeignKey("FilhoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Usuarios.API.Domain.Entities.Mesada", "Mesada")
                        .WithMany()
                        .HasForeignKey("MesadaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Filho");

                    b.Navigation("Mesada");
                });

            modelBuilder.Entity("Usuarios.API.Domain.Entities.Tarefa", b =>
                {
                    b.HasOne("Usuarios.API.Domain.Entities.Filho", "Filho")
                        .WithMany()
                        .HasForeignKey("FilhoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Filho");
                });

            modelBuilder.Entity("Usuarios.API.Domain.Entities.Filho", b =>
                {
                    b.HasOne("Usuarios.API.Domain.Entities.Usuario", null)
                        .WithOne()
                        .HasForeignKey("Usuarios.API.Domain.Entities.Filho", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Usuarios.API.Domain.Entities.Pai", b =>
                {
                    b.HasOne("Usuarios.API.Domain.Entities.Usuario", null)
                        .WithOne()
                        .HasForeignKey("Usuarios.API.Domain.Entities.Pai", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Usuarios.API.Domain.Entities.Pai", b =>
                {
                    b.Navigation("PaisFilhos");
                });
#pragma warning restore 612, 618
        }
    }
}
